export const coursedata = [
  {
    id: 1,
    title: "some text",
    description: "some text",
    duration: "1hour",
    prerequisites: "some text",
    formate: "some text",
    materials: "some text",
    assesment: "some text",
    fee: "1000",
  },
  {
    id: 2,
    title: "some text",
    description: "some text",
    duration: "1hour",
    prerequisites: "some text",
    formate: "some text",
    materials: "some text",
    assesment: "some text",
    fee: "1000",
  },
  {
    id: 3,
    title: "some text",
    description: "some text",
    duration: "1hour",
    prerequisites: "some text",
    formate: "some text",
    materials: "some text",
    assesment: "some text",
    fee: "1000",
  },
  {
    id: 4,
    title: "some text",
    description: "some text",
    duration: "1hour",
    prerequisites: "some text",
    formate: "some text",
    materials: "some text",
    assesment: "some text",
    fee: "1000",
  },
  {
    id: 5,
    title: "some text",
    description: "some text",
    duration: "1hour",
    prerequisites: "some text",
    formate: "some text",
    materials: "some text",
    assesment: "some text",
    fee: "1000",
  },
];
