import Im from "./event1/images/card.png";
const EventsCard = [
  {
    id: 1,
    url: Im,
    title: "title one",
    para: "Instructors   love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy.",
    img: [
      "https://swiperjs.com/demos/images/nature-1.jpg",
      "https://swiperjs.com/demos/images/nature-2.jpg",
      "https://swiperjs.com/demos/images/nature-3.jpg",
      "https://swiperjs.com/demos/images/nature-4.jpg",
      "https://swiperjs.com/demos/images/nature-1.jpg",
      "https://swiperjs.com/demos/images/nature-2.jpg",
      "https://swiperjs.com/demos/images/nature-3.jpg",
      "https://swiperjs.com/demos/images/nature-4.jpg",
      "https://swiperjs.com/demos/images/nature-1.jpg",
      "https://swiperjs.com/demos/images/nature-2.jpg",
      "https://swiperjs.com/demos/images/nature-3.jpg",
      "https://swiperjs.com/demos/images/nature-4.jpg",
    ],
  },
  {
    id: 2,
    url: Im,
    title: "title two",
    img: [
      "https://swiperjs.com/demos/images/nature-1.jpg",
      "https://swiperjs.com/demos/images/nature-2.jpg",
      "https://swiperjs.com/demos/images/nature-3.jpg",
      "https://swiperjs.com/demos/images/nature-4.jpg",
      "https://swiperjs.com/demos/images/nature-1.jpg",
      "https://swiperjs.com/demos/images/nature-2.jpg",
      "https://swiperjs.com/demos/images/nature-3.jpg",
      "https://swiperjs.com/demos/images/nature-4.jpg",
      "https://swiperjs.com/demos/images/nature-1.jpg",
      "https://swiperjs.com/demos/images/nature-2.jpg",
      "https://swiperjs.com/demos/images/nature-3.jpg",
      "https://swiperjs.com/demos/images/nature-4.jpg",
    ],
    para: "Instructors   love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy.",
  },
  {
    id: 3,
    url: Im,
    title: "title three",
    img: [
      "https://swiperjs.com/demos/images/nature-1.jpg",
      "https://swiperjs.com/demos/images/nature-2.jpg",
      "https://swiperjs.com/demos/images/nature-3.jpg",
      "https://swiperjs.com/demos/images/nature-4.jpg",
      "https://swiperjs.com/demos/images/nature-1.jpg",
      "https://swiperjs.com/demos/images/nature-2.jpg",
      "https://swiperjs.com/demos/images/nature-3.jpg",
      "https://swiperjs.com/demos/images/nature-4.jpg",
      "https://swiperjs.com/demos/images/nature-1.jpg",
      "https://swiperjs.com/demos/images/nature-2.jpg",
      "https://swiperjs.com/demos/images/nature-3.jpg",
      "https://swiperjs.com/demos/images/nature-4.jpg",
    ],
    para: "Instructors   love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy.",
  },
  {
    id: 4,
    url: Im,
    title: "title four",
    img: [
      "https://swiperjs.com/demos/images/nature-1.jpg",
      "https://swiperjs.com/demos/images/nature-2.jpg",
      "https://swiperjs.com/demos/images/nature-3.jpg",
      "https://swiperjs.com/demos/images/nature-4.jpg",
      "https://swiperjs.com/demos/images/nature-1.jpg",
      "https://swiperjs.com/demos/images/nature-2.jpg",
      "https://swiperjs.com/demos/images/nature-3.jpg",
      "https://swiperjs.com/demos/images/nature-4.jpg",
      "https://swiperjs.com/demos/images/nature-1.jpg",
      "https://swiperjs.com/demos/images/nature-2.jpg",
      "https://swiperjs.com/demos/images/nature-3.jpg",
      "https://swiperjs.com/demos/images/nature-4.jpg",
    ],
    para: "Instructors   love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy.",
  },
  {
    id: 5,
    url: Im,
    title: "title five",
    img: [
      "https://swiperjs.com/demos/images/nature-1.jpg",
      "https://swiperjs.com/demos/images/nature-2.jpg",
      "https://swiperjs.com/demos/images/nature-3.jpg",
      "https://swiperjs.com/demos/images/nature-4.jpg",
      "https://swiperjs.com/demos/images/nature-1.jpg",
      "https://swiperjs.com/demos/images/nature-2.jpg",
      "https://swiperjs.com/demos/images/nature-3.jpg",
      "https://swiperjs.com/demos/images/nature-4.jpg",
      "https://swiperjs.com/demos/images/nature-1.jpg",
      "https://swiperjs.com/demos/images/nature-2.jpg",
      "https://swiperjs.com/demos/images/nature-3.jpg",
      "https://swiperjs.com/demos/images/nature-4.jpg",
    ],
    para: "Instructors   love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.Instructors from around the world teach millions of students on Udemy.",
  },
];
export default EventsCard;
